### ISSUE TITLE
Add files and Drop Files Here not working in Demo Instance

### ISSUE THREAD

**Issue by gamontoya** [samvera-labs/hyku#881]
### Descriptive summary

**Adding file(s)** and **Drop Files Here** is not working. Tested on various browsers to make sure the issue wasn't browser related.

- https://a11y.demo.hydrainabox.org/

### Expected behavior
- Files are added to my work and thumbnails are generated.

### Actual behavior
- Clicked on Add File, navigated to my images and nothing happened.
- Drag/dropped my image and the browser rendered the image and nothing more.

**Comment by jcoyne** [comment]
Should be fixed now.

**Comment by jcoyne** [comment]
@gamontoya What do you mean by "local files" can you screenshot where you see that?

**Comment by gamontoya** [comment]
@jcoyne 
- Add files or Add Local Files

![hyrax](https://cloud.githubusercontent.com/assets/4314914/24219089/d9dc451e-0f02-11e7-9905-4dca59913bd6.png)

**Comment by jcoyne** [comment]
Thanks @gamontoya. Would you mind retesting today and let me know if you still have the same errors? We had a big Javascript issue yesterday that has since been fixed.

**Comment by gamontoya** [comment]
@jcoyne I actually just had tested when I create the above screenshot. I still can't drag/drop files either.

**Comment by gamontoya** [comment]
@jcoyne Do you have a browser preference?

**Comment by jcoyne** [comment]
What ever you were using the other day.

**Comment by jcoyne** [comment]
@gamontoya can you tell me what browser you are using?

**Comment by gamontoya** [comment]
@jcoyne That's still a **no** from me. I'm using the latest Chrome.

**Comment by jcoyne** [comment]
It works for me on Chrome 57 on OS X. What version and operating system are you using?  Are you able to do drag and drop uploads on other websites such as gmail?

**Comment by gamontoya** [comment]
@jcoyne I'm using Chrome 57, on Windows 7. I can try on Windows 10 from my home computer if that would help. And yes, I can drag/drop files from my desktop to Gmail with no problem.

![chrome](https://cloud.githubusercontent.com/assets/4314914/24221894/596ec28e-0f0d-11e7-9d14-413fe96a72be.png)

**Comment by jcoyne** [comment]
That would be super helpful if you checked your home computer too.  It would be great if we could figure out which browser and OS combinations where it's broken.

**Comment by gamontoya** [comment]
I can tell you things don't look too pretty in Firefox either. But, I'll test on Windows 10 today and on my Mac tomorrow.

**Comment by mjgiarlo** [comment]
Thanks for helping us troubleshoot, @gamontoya!

**Comment by gamontoya** [comment]
- @mjgiarlo My pleasure.
- @jcoyne To add to my list:

The add or drop files functionality is not working for me on Windows 10 / 64 bit using Chrome 57 or Edge 38.14

![edge](https://cloud.githubusercontent.com/assets/4314914/24225610/b3420472-0f1e-11e7-9258-6258126c9a72.png)

I will try tomorrow with my Mac.

**Comment by gamontoya** [comment]
Now it no longer clear if it is me or...

* Mac OS X
     * Chrome 57
          * Add files: Browse to desktop, choose image, nothing happens
          * Drag and drop: Images renders in browser
     * Safari 9.1.2
          * Same behavior as listed above for Chrome.

![screen shot 2017-03-23 at 10 24 17 am](https://cloud.githubusercontent.com/assets/4314914/24261647/e16fcd52-0fb4-11e7-82b3-a77b82132686.png)

![screen shot 2017-03-23 at 10 25 03 am](https://cloud.githubusercontent.com/assets/4314914/24261653/e7ce335a-0fb4-11e7-8cdb-cce1b045d540.png)

![screen shot 2017-03-23 at 10 27 16 am](https://cloud.githubusercontent.com/assets/4314914/24261663/f0671568-0fb4-11e7-97cb-939c13fce6e8.png)

I suppose someone could go into my two *Works* and see if they can add files. Any other ideas?

**Comment by hannahfrost** [comment]
I'm chalking this one up to an old issue that no one could possibly reproduce. If it happens again, let us know and we'll take a look!
